name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: supa-framework/supa-framework/.github/workflows/ci.yml@main
    with:
      app-slug: "{{APP_SLUG}}"
      strictness: "{{STRICTNESS}}"
    secrets: inherit
